//
// errors.h
//

// here we shall define all the error strings
// instead of having them scattered all across
// the codebase in a raw form.
//
// also, for each error, we will use a code number
// which will be of the form E<NUMBER>.

#pragma once

/* errors originating in lexer */
#define E001 "error E001: Included file path not specified."
#define E002 "error E002: Invalid string provided for included file path."
#define E003 "error E003: #define is missing a definition."
#define E004 "error E004: #define definition must begin with either an alphabet or underscore."
#define E005 "error E005: #define definition is incomplete."
#define E006 "error E006: Invalid #define statement: Only alpha-numerics or underscores are allowed."
#define E007 "error E007: Invalid #define statement: Invalid numeric literal"
#define E008 "error E008: Invalid preprocessor directive encountered."
#define E009 "error E009: Invalid token. Identifiers cannot start with numeric characters."
#define E010 "error E010: Invalid character literal"
#define E011 "error E011: Invalid character literal. Closing quote not found."
#define E012 "error E012: Invalid character \'\\t\' in string literal"
#define E013 "error E013: Invalid string literal. Closing quote not found."
#define E014 "error E014: Invalid token encountered."
#define E083 "error E083: #undef must be provided a definition."
#define E084 "error E084: #ifdef/#ifndef must be provided a definition."
#define E085 "error E085: \'#\' must be the first non-whitespace character on a line."
#define E086 "error E086: Included file name must be in the format: <FILE_NAME>.<EXTENSION>"
#define E087 "error E087: Could not find the file: %s"
#define E107 "error E107: Invalid escape sequence encountered."

/* errors originating in parser */
#define E015 "\nerror E015: Could not find current token."
#define E016 "error E016: Insufficient tokens for function definition."
#define E017 "error E017: Missing delimiter \';\' at the end of the statement."
#define E018 "error E018: Incomplete function call expression."
#define E019 "error E019: Invalid expression. Used \';\' in an expression that is not a statement."
#define E020 "error E020: Missing \'}\' from scope."
#define E021 "error E021: Incomplete \'if\' statement encountered."
#define E022 "error E022: Missing \'(\' from if statement condition."
#define E023 "error E023: \'if\' condition cannot contain a keyword."
#define E024 "error E024: Incomplete \'else\' statement encountered."
#define E025 "error E025: Incomplete \'for\' statement encountered."
#define E026 "error E026: Missing \'(\' from for statement condition."
#define E027 "error E027: Incomplete \'for\' statement encountered."
#define E028 "error E028: \'for\' initialization cannot contain a keyword."
#define E029 "error E029: \'for\' condition cannot contain a keyword."
#define E030 "error E030: \'for\' loop expression cannot contain a keyword."
#define E031 "error E031: Incomplete \'while\' statement encountered."
#define E032 "error E032: Missing \'(\' from while statement condition."
#define E033 "error E033: \'while\' condition cannot contain a keyword."
#define E034 "error E034: Incomplete \'return\' statement encountered."
#define E035 "error E035: return statement cannot contain another keyword."
#define E036 "error E036: Undefined function encountered."
#define E037 "error E037: Missing arguments in function call."
#define E038 "error E038: Undeclared identifier encountered."
#define E039 "error E039: Invalid declaration. Data type not specified for identifier."
#define E040 "error E040: Invalid declaration. Missing identifier after data type"
#define E041 "error E041: Invalid declaration. A variable with this name already exists in the current / parent scope."
#define E042 "error E042: Missing expression after \'(\'."
#define E043 "error E043: Unary prefix operator must be followed by an expression."
#define E044 "error E044: Failed to parse primary expression."
#define E045 "error E045: Invalid expression. Expected binary operator."
#define E046 "error E046: Invalid expression. Expected identifier/literal."
#define E047 "error E047: Missing delimiter at the end of expression."
#define E048 "error E048: This keyword cannot occur at the start of an expression."
#define E049 "error E049: Invalid data type for function parameter."
#define E050 "error E050: Invalid identifier for function parameter."
#define E051 "error E051: Invalid parameter name. A variable with this name already exists."
#define E052 "error E052: Missing separator (\',\') in function parameters."
#define E053 "error E053: Invalid return type for function definition."
#define E054 "error E054: Invalid identifier used in function definition."
#define E055 "error E055: Invalid function definition. Function with the same name already exists."
#define E056 "error E056: Missing token \'(\' in function definition."
#define E057 "error E057: Function definition must be followed by a statement."
#define E058 "error E058: Function prototype with this name already exists."
#define E059 "error E059: Missing expression after \'=\' in global variable initialization."
#define E060 "error E060: No tokens found."
#define E061 "error E061: Incomplete top-level expression encountered."
#define E062 "error E062: Duplicate entry points found."
#define E088 "error E088: Invalid function definition: Variadic arg marker \'...\' must be followed by \')\'."
#define E089 "error E089: Invalid varg syntax: Expected \'(\'."
#define E090 "error E090: Invalid varg syntax: Expected data type."
#define E091 "error E091: Invalid varg syntax: Expected \')\'."
#define E092 "error E092: Incomplete switch expression encountered."
#define E093 "error E093: Switch expression must be followed by an identifier."
#define E094 "error E094: Missing \')\' from switch expression."
#define E095 "error E095: Missing \'{\' from switch expression."
#define E096 "error E096: Expected \'case\' keyword inside switch block."
#define E097 "error E097: Missing or invalid literal used in case expression."
#define E098 "error E098: Only integer or string literals are allowed in case expressions."
#define E099 "error E099: Missing \':\' in case expression."
#define E100 "error E100: Duplicate default case found in switch block."
#define E102 "error E102: Switch expressions can only accept integer or string types."
#define E103 "error E103: Invalid data type encountered."
#define E104 "error E104: Invalid top-level expression encountered. This keyword cannot be used at the global scope."
#define E105 "error E105: Incomplete typedef statement encountered."
#define E106 "error E106: typedef definition must be a valid type."
#define E108 "error E108: enum keyword must be followed by the enum type name."
#define E109 "error E109: Missing \'{\' from enum statement."
#define E110 "error E110: Expected an enum identifier."
#define E111 "error E111: Incomplete enum statement encountered."
#define E112 "error E112: Expected integer literal for enum value."
#define E113 "error E113: Expected \';\' at the end of enum statement."

/* errors originating in ir_generator */
#define E063 "error E063: Non-integer type in logical expression."
#define E064 "error E064: Undefined identifier encountered."
#define E065 "error E065: Unidentified literal type encountered."
#define E066 "error E066: Explicit return could not be found in function block for a function with non-void return type."
#define E067 "error E067: Invalid function. Could not be verified."
#define E068 "error E068: (FATAL) Cannot find parent IR block for \'if\' statement."
#define E069 "error E069: (FATAL) Cannot find parent IR block for \'for\' statement."
#define E070 "error E070: (FATAL) Cannot find parent IR block for \'while\' statement."
#define E071 "error E071: (FATAL) Cannot find parent IR block for declaration."
#define E072 "error E072: Cannot increment/decrement a non-lvalue expression."
#define E073 "error E073: Invalid unary operator encountered."
#define E074 "error E074: (FATAL) Cannot find parent IR block for function call."
#define E075 "error E075: Invalid function call."
#define E076 "error E076: Return value type does not match the function return type."
#define E077 "error E077: \'break\'/\'continue\' cannot be used outside a loop."
#define E078 "error E078: Invalid jump type encountered."
#define E079 "error E079: (FATAL) Cannot find parent IR block for jump statement."
#define E080 "error E080: Global declaration can only be of assignment type."
#define E081 "error E081: Global initializers must be constant expressions."
#define E082 "error E082: Invalid top-level expression encountered."
#define E101 "error E101: (FATAL) Cannot find parent IR block for \'switch\' statement."
